// <auto-generated />
namespace MCY_CV3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TechKnow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TechKnow));
        
        string IMigrationMetadata.Id
        {
            get { return "202008211552232_TechKnow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
